# Generated by Django 4.2.6 on 2023-10-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='password', max_length=40),
        ),
    ]
