# Generated by Django 4.2.6 on 2023-10-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='document',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
