# Generated by Django 4.2.6 on 2023-10-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_roles_rol_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='rol_name',
            field=models.CharField(max_length=30),
        ),
    ]
